apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-push
spec:
  params:
    - name: git-url
      type: string
    - name: git-revision
      type: string
  workspaces:
    - name: source
  steps:
    - name: push
      image: alpine/git
      script: |
        cd $(workspaces.source.path)
        git add .
        git commit -m "Updated container version"
        git push $(params.git-url) $(params.git-revision)
