apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: helm-update
spec:
 params:
    - name: chart-path
      type: string
    - name: new-image
      type: string
  workspaces:
    - name: source
  steps:
    - name: update-helm
      image: alpine
      script: |
        cd $(workspaces.source.path)/$(params.chart-path)
        sed -i 's|image: .*|image: $(params.new-image)|' values.yaml
