apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: helm-update
spec:
  params:
    - name: chart-url
      type: string
  steps:
    - name: update-chart
      image: alpine/git
      script: |
        git clone $(params.chart-url) /chart
        cd /chart
        sed -i 's/tag:.*/tag: $(params.IMAGE)/' values.yaml
